# Copyright 2016 Apcera Inc. All rights reserved.
cache:
  directories:
    - $HOME/gnatsd
before_install:
  - bash ./scripts/install_gnatsd.sh
before_script:
  - export PATH=$HOME/gnatsd:$PATH
language: elixir
otp_release:
  - 19.2
  - 20.3
  - 21.2
elixir:
  - 1.5.3
  - 1.6.6
  - 1.7.4
matrix:
  exclude:
    - otp_release: 21.2
      elixir: 1.5.3
sudo: false
script:
  - ./test/run-test-servers.sh < /dev/null 2>&1 &
  - 'MIX_ENV=test mix do deps.get, compile, coveralls.travis'
